export const AUTH_REQUEST = "AUTH_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";
//
//
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
//
export const CREATE_POST_SET_DATA = "CREATE_POST_SET_DATA";
export const CREATE_POST_RESETSET_DATA = "CREATE_POST_RESETSET_DATA";
//
export const ALL_USERS = "ALL_USERS";
export const CURRENT_USERS = "CURRENT_USERS";
